;

export async function sendHelpMessage(ctx: any) {
    const chatId = ctx.chat.id;
    const helpMessage = `
<b>DRIBx bot - Help & Information</b>

<i>🌟 Current Features</i>
<b>Exchange Integration:</b> DRIBx bot is currently integrated with Raydium. Stay tuned for our upcoming integration with Jupiter, expanding your trading possibilities!
<b>Fees:</b> We are committed to transparency and affordability. Currently, our transaction fee is only 0%. Note that this fee may increase in the future to support exciting features.

<i>🔜 What’s Coming</i>
<b>Jupiter Integration:</b> We're working hard to connect DRIBx bot to Jupiter. This will offer you more trading options and enhance your trading experience.

<i>💸 Referral Program</i>
<b>Limited Availability:</b> We offer a very limited referral program. Invite your friends to join DRIBx bot and benefit from our exclusive offers. Keep an eye out for updates on this!

<i>🤝 Partnership Program Development</i>
<b>Post-Premium Launch:</b> Following the release of all our premium features, we're excited to be developing a partnership program. Stay tuned for more details!

<i>🔧 How to Use DRIBx bot</i>
<b>Trading:</b> To start trading, simply choose a Solana pair (SPL token) on Raydium, and DRIBx bot will handle the rest.
<b>Wallet Management:</b> Enjoy flexible wallet options with DRIBx bot. You have two choices:
1. <b>Auto-Generated Wallet:</b> Get started quickly with a wallet automatically generated by DRIBx bot.
2. <b>Import & Reset:</b> Prefer to use your existing wallet? Easily import it into DRIBx bot. Plus, you have the freedom to reset and change your wallet at any time. Simply use the Wallets & settings button to manage your wallets efficiently.

<i>🤝 Support & Community</i>
Have more questions or need assistance? Join our thriving community on Telegram for support, updates, and more: <a href='https://t.me/DRIBx botChat'>Join DRIBx bot Telegram Group</a>

<b>📈 Trade Smart, Trade with DRIBx bot!</b>
    `;

    ctx.api.sendMessage(chatId, helpMessage, {
        parse_mode: 'HTML',
        reply_markup: {
            inline_keyboard: [[{ text: 'Exit', callback_data: 'closing' }]]
        }
    });
}

export async function sendReferMessage(ctx: any) {
    const chatId = ctx.chat.id;
    await ctx.api.sendMessage(chatId, "Stay tuned for our upcoming referral program! 🌟 We'll soon be announcing all the details about how you can earn rewards by referring friends to our platform. Keep an eye out for our announcement");
}