;

export async function sendHelpMessage(ctx: any) {
    const chatId = ctx.chat.id;
    const helpMessage = `
<b>DRIB bot - Help & Information</b>

<i>🌟 Current Features</i>
<b>Exchange Integration:</b> DRIB bot is currently integrated with Raydium. Stay tuned for our upcoming integration with Jupiter, expanding your trading possibilities!
<b>Fees:</b> We are committed to transparency and affordability. Currently, our transaction fee is only 0.8%. Note that this fee may increase in the future to support exciting features.

<i>🔜 What’s Coming</i>
<b>Jupiter Integration:</b> Our bot is evolving, promising to enhance your trading experience with more options and flexibility.

<i>💸 Referral Program</i>
<b>Exclusive Early Access:</b> We're introducing a limited availability referral program. Invite your friends to join the DRIB bot and gain early access to our premium features. Stay tuned for more updates!

<b>NFT for Early Access:</b> We're leveraging the power of NFTs to offer you early access to our referral program and premium features. This is your ticket to a world of exclusive benefits with DRIB bot.

<b>Free Trading FOR LIFE:</b> Yes, you read that right. We're offering no trading fees for LIFE. This is a golden opportunity to trade freely with the upcoming tools of DRIB bot, enhancing your trading experience without any cost.

<b>Future Airdrops:</b> To reward our loyal DRIBs users, we're planning future airdrops. This is our way of saying thank you for your continued support and trust in us.

Remember, these exciting features and offers are on the horizon. Join us in this journey and let's shape the future of trading together!

<i>🤝 Partnership Program Development</i>
<b>Post-Premium Launch:</b> Following the release of all our premium features, we're excited to be developing a partnership program. Stay tuned for more details!

<i>🔧 How to Use DRIB bot</i>
<b>Trading:</b> To start trading, simply choose a Solana pair (SPL token) on Raydium, and DRIB bot will handle the rest.
<b>Wallet Management:</b> Enjoy flexible wallet options with DRIB bot. You have two choices:
1. <b>Auto-Generated Wallet:</b> Get started quickly with a wallet automatically generated by DRIB bot.
2. <b>Import & Reset:</b> Prefer to use your existing wallet? Easily import it into DRIB bot. Plus, you have the freedom to reset and change your wallet at any time. Simply use the Wallets & settings button to manage your wallets efficiently.

<i>🤝 Support & Community</i>
Have more questions or need assistance? Join our thriving community on Telegram for support, updates, and more: <a href='https://t.me/DRIB botChat'>Join DRIB bot Telegram Group</a>

<b>📈 Trade Smart, Trade with DRIB bot!</b>
    `;

    ctx.api.sendMessage(chatId, helpMessage, {
        parse_mode: 'HTML',
        reply_markup: {
            inline_keyboard: [[{ text: 'Exit', callback_data: 'closing' }]]
        }
    });
}

export async function sendReferMessage(ctx: any) {
    const chatId = ctx.chat.id;
    await ctx.api.sendMessage(chatId, "Stay tuned for our upcoming referral program! 🌟 We'll soon be announcing all the details about how you can earn rewards by referring friends to our platform. Keep an eye out for our announcement");
}